parameters:
    acilia.view.counter:
        realtime: false

services:
    acilia.view.counter:
        class: Acilia\Bundle\ViewCounterBundle\Service\ViewCounterService
        arguments: [@doctrine, @core.memcached, %acilia.view.counter%]
